---
# set up subscription refresh mechanism
- name: Copy subscription refreshment script
  copy:
    src: ../files/refresh_subscriptions.sh
    dest: /root/refresh_subscriptions.sh
    owner: root
    group: root
    mode: 755

- name: Copy saved iptable rules
  copy:
    src: ../files/etc/iptables/rules.v4
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 755

- name: Copy systemd service file of iptable rules
  copy:
    src: ../files/etc/systemd/tproxy-rules.service
    dest: /etc/systemd/tproxy-rules.service
    owner: root
    group: root
    mode: 755

- name: enable v2ray
  service:
    name: v2ray
    enabled: yes

- name: enable tproxy-rules
  service:
    name: tprrxy-rules
    enabled: yes

- name: Start v2ray
  script: ../files/refresh_subscriptions.sh {{subscription_url}}

- name: Routing strategy
  script: ../files/iptables_provision.sh

- name: Enable ip forwarding(1)
  lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1

- name: Enable ip forwarding(2)
  command:
    cmd: sysctl -p

- name: Ensure the subscription updated everyday
  cron:
    name: "update subscriptions"
    minute: "0"
    hour: "5"
    job: "/root/refresh_subscriptions.sh {{subscription_url}} >> /var/log/refresh_subscriptions.log"
