---
dependencies:
  - role: jellycsc.v2ray
  - role: christiangda.amazon_cloudwatch_agent
    vars:
      cwa_agent_mode: onPremise
      cwa_aws_region: "{{aws_region}}"
      cwa_profile: "default"
      cwa_agent_profile_path: /root
      cwa_conf_json_file_content:
        agent:
          metrics_collection_interval: 300
          region: "{{aws_region}}"
        metrics:
          metrics_collected:
            cpu:
              measurement:
                - usage_idle
                - usage_guest
            disk:
              resources:
                - "/"
              measurement:
                - total
                - used
              drop_device: true
            mem:
              measurement:
                - total
                - used
            net:
              measurement:
                - bytes_sent
                - bytes_recv
        logs:
          logs_collected:
            files:
              collect_list:
                - file_path: "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
                  log_group_name: micro-dev
                  log_stream_name: amazon-cloudwatch-agent.log
                  timezone: UTC
